version: '3.4'

services:
  nadin.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_ENVIRONMENT=Production
      - "ConnectionStrings:DefaultConnection=Server=nadindatabase;Database=NadinDB;User Id=sa;Password=Aa123456;TrustServerCertificate=True"
      - "BearerTokens:Key=NadinSystemRandomKeyToken"
      - "BearerTokens:Issuer=http://localhost:7000/"
      - "BearerTokens:RefreshTokenExpirationMinutes=30"
      - "BearerTokens:AccessTokenExpirationMinutes=15"
      - "BearerTokens:ClockSkew=1"
      - "CacheSettings:ConnectionString=redisdb"
    ports:
      - "7000:80"
      - "7001:443"
    volumes:
      - nadin_data:/root/.microsoft/usersecrets:ro
      - nadin_data:/root/.aspnet/https:ro
    depends_on: 
      - nadindatabase
      - redisdb
    networks:
       - nadin-network

  redisdb: 
    container_name: redisdb
    restart: always
    ports:
      - "6379:6379"
    networks:
       - nadin-network

  nadindatabase:
    container_name: nadindatabase
    environment:
      SA_PASSWORD: "Aa123456"
      ACCEPT_EULA: "Y"
    restart: always
    # volumes:
    #   - mssql_data:/var/opt/mssql
    ports:
      - "1433:1433"
    networks:
       - nadin-network

volumes:
  mssql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      #device: /var/opt/mssql
      device: c:/DockerVolumes/mssql

  nadin_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      #device: /var/opt/mssql
      device: c:/DockerVolumes/nadin

networks:
  nadin-network:
    driver: bridge